# Generated by Django 4.1.5 on 2023-01-22 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(max_length=255, null=True)),
                ("line3", models.CharField(max_length=255, null=True)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
