permissions:
  id-token: write
  contents: read

name: CI Pipeline
# Only run one deploy at a time for a given branch
concurrency: ci-${{ github.ref_name }}

on:
  push:

env:
  DJANGO_DB_ENGINE: postgresql

jobs:
  linting:
    name: Linting
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Poetry install
        run: poetry install --with dev
      - name: Lint
        run: |
          export PYTHONPATH=${PYTHONPATH}:./src/mimir/web_app:./src/
          make lint-ci

  tests:
    name: Test
    needs: [linting]
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    services:
      postgres:
        image: postgres:15
        env:
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_DB: mimir-db-test
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Poetry install
        run: poetry install --with dev
      - name: Run tests
        env:
          ENVIRONMENT: TEST
          DJANGO_DB_ENGINE: postgresql
          DJANGO_DB_NAME: mimir-db-test
          DJANGO_DB_USER: postgres
          DJANGO_DB_PASSWORD: postgres
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
        run: |
          export PYTHONPATH=${PYTHONPATH}:./src/mimir/web_app:./src/
          make migrate
          make test
