permissions:
  id-token: write
  contents: read

name: CI Pipeline
# Only run one deploy at a time for a given branch
concurrency: ci-${{ github.ref_name }}

on:
  push:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.3.2"]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Poetry install
        run: poetry install --group dev
      - name: Lint
        run: make lint